package com.letbeclear.model;
// Generated Feb 12, 2018 12:30:31 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "letbeclear")
public class UserProfile implements java.io.Serializable {

	private long userId;
	private Users users;
	private String gender;
	private String photo;
	private String displayname;
	private String maritalstatus;
	private Date dateofbirth;
	private Integer field1;
	private String field2;
	private Date field3;

	public UserProfile() {
	}

	public UserProfile(Users users, Date dateofbirth, Date field3) {
		this.users = users;
		this.dateofbirth = dateofbirth;
		this.field3 = field3;
	}

	public UserProfile(Users users, String gender, String photo, String displayname, String maritalstatus,
			Date dateofbirth, Integer field1, String field2, Date field3) {
		this.users = users;
		this.gender = gender;
		this.photo = photo;
		this.displayname = displayname;
		this.maritalstatus = maritalstatus;
		this.dateofbirth = dateofbirth;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "USER_ID", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "GENDER", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "PHOTO", length = 512)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "DISPLAYNAME", length = 256)
	public String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	@Column(name = "MARITALSTATUS", length = 28)
	public String getMaritalstatus() {
		return this.maritalstatus;
	}

	public void setMaritalstatus(String maritalstatus) {
		this.maritalstatus = maritalstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEOFBIRTH", nullable = false, length = 19)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 256)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FIELD3", nullable = false, length = 19)
	public Date getField3() {
		return this.field3;
	}

	public void setField3(Date field3) {
		this.field3 = field3;
	}

}
